// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerInfo } from "../McpServerInfo";
import type { Resource } from "../Resource";
import type { ResourceTemplate } from "../ResourceTemplate";
import type { Tool } from "../Tool";
import type { McpAuthStatus } from "./McpAuthStatus";
import type { McpServerConnectionStatus } from "./McpServerConnectionStatus";
import type { McpServerStartupFailureReason } from "./McpServerStartupFailureReason";

export type McpServerStatus = { name: string,
/**
 * Current thread-runtime connection state; null when unavailable or the configuration changed.
 */
runtimeStatus: McpServerConnectionStatus | null,
/**
 * User-safe detail for the current thread-runtime startup failure, when one is retained.
 */
error: string | null,
/**
 * Typed recovery reason for the current thread-runtime startup failure, when known.
 */
failureReason: McpServerStartupFailureReason | null, pluginId: string | null, serverInfo: McpServerInfo | null, tools: { [key in string]?: Tool }, resources: Array<Resource>, resourceTemplates: Array<ResourceTemplate>, authStatus: McpAuthStatus, };
