// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy-history compatibility for older Desktop clients; paginated histories use `thread/revert`.
 */
export type ThreadRollbackParams = { threadId: string,
/**
 * Number of trailing turns to remove, at least one. This does not revert file changes.
 */
numTurns: number, };
